baseurl = "http://kicad-pcb.org/"
languageCode = "en-us"
title = "KiCad EDA"
canonifyurls = true
layoutdir = "layouts"

[params]
	DateForm = "Mon, Jan 2, 2006"
	Description = "A Cross Platform and Open Source Electronics Design Automation Suite"
	Author = "The KiCad editors"
	Forum = "https://forum.kicad.info/"
	Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/kicad_pcb"
[[params.social]]
  title = "github"
  url = "https://github.com/KiCad"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/kicadpcb"

[[menu.main]]
    name   = "Blog"
    url    = "/post"
    weight = -200

[[menu.main]]
    name   = "Download"
    url    = "/download"
    weight = 600

[[menu.main]]
    name   = "Contribute"
    weight = 500

[[menu.main]]
    name   = "Community"
    weight = 10
[[menu.main]]
    parent = "Community"
    name   = "User Forum"
    url    = "http://forum.kicad.info/"
    weight = 10
[[menu.main]]
    parent = "Community"
    name   = "User Mailing List"
    url    = "http://groups.yahoo.com/group/kicad-users/"
    weight = 15
[[menu.main]]
    parent = "Community"
    name   = "kicad.jp"
    url    = "http://kicad.jp/"
    weight = 20


[[menu.main]]
    name   = "Help"
    weight = 0
[[menu.main]]
    parent = "Help"
    name   = "Users's Manual"
    url    = "http://docs.kicad-pcb.org/"
    weight = 20
[[menu.main]]
    name   = "Report a Bug"
    url    = "https://bugs.launchpad.net/kicad/+bugs?orderby=-date_last_updated&start=0"
    parent = "Help"
    weight = 35
[[menu.main]]
    parent = "Help"
    name   = "FAQ"
    url    = "http://www.kicad-pcb.org/display/KICAD/Frequently+Asked+Questions"
    weight = 60
