baseurl = "/"
languageCode = "en-us"
title = "KiCad EDA"
canonifyurls = false
layoutdir = "layouts"
pluralizelisttitles = false
disablePathToLower = true

[outputs]
    home     = ["HTML"]
    section  = ["HTML", "RSS"]

[taxonomies]
    category = "categories"
    blog_categories = "blog/categories"

[params]
    DateForm = "2006-01-02"
    Description = "A Cross Platform and Open Source Electronics Design Automation Suite"
    Author = "The KiCad editors"
    Forum = "https://forum.kicad.info/"

[permalinks]
    klc = "/libraries/klc/:filename/"
    blog = "blog/:year/:month/:slug"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/kicad_pcb"
[[params.social]]
    title = "gitlab"
    url = "https://gitlab.com/KiCad"

[[menu.main]]
    name   = "Blog"
    url    = "/blog/"
    weight = 1

[[menu.main]]
    name = "Discover"
    weight = 5

[[menu.main]]
    parent = "Discover"
    name   = "Made With KiCad"
    url    = "/made-with-kicad/"
    weight = 50

[[menu.main]]
    parent = "Discover"
    name   = "External Tools"
    url    = "/external-tools/"
    weight = 60

[[menu.main]]
    name   = "Community"
    weight = 10

[[menu.main]]
    parent = "Community"
    name   = "Forums"
    url    = "/community/sites#_forums"
    weight = 10

[[menu.main]]
    parent = "Community"
    name   = "User Mailing List"
    url    = "https://groups.io/g/kicad-users"
    weight = 15

[[menu.main]]
    name   = "Help"
    weight = 100

[[menu.main]]
    parent = "Help"
    name   = "Documentation"
    url    = "http://docs.kicad-pcb.org"
    weight = 10

[[menu.main]]
    name   = "Contribute"
    weight = 500

[[menu.main]]
    name = "Libraries"
    weight = 550

[[menu.main]]
    name   = "Download"
    url = "/download/"
    weight = 600

[[menu.main]]
    name   = "About"
    weight = 900
